#1083 installing datadog into our app
department-of-veterans-affairs/notification-api pull request #1084
Opened 2023-02-12 21:01 UTC by ldraney

# Description

#issue 1083 Install Datadog APM
This PR adds snippets from Datadogs documentation to install APM into our application
And adds addition commands to start its service

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Successfully shows up in Datadog Dashboard after a successful deployment through our pipeline
- [ ] Test B  (to be determined)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

2023-02-28 16:38 UTC, k-macmillan requested changes
The formatting is very inconsistent. Please fix the formatting of the task definitions.

2023-02-28 17:30 UTC, cris-oddball requested changes

2023-02-28 17:30 UTC, cris-oddball commented on requirements.txt
> +alembic==1.9.4
This comment applies to requirements.txt, requirements-app.txt, and requirements_for_test.txt. 

I don't understand why so many dependencies are changed for Datadog APM. You had mentioned that you had merged master into this branch, but none of these changes are on master (which is why they are showing as changed in this PR). 

We would need extensive testing to ensure compatibility here and the Flask upgrade might be taking care of most of these. 

Can these files only be changed for what DD APM actually needs?

2023-03-02 14:42 UTC, k-macmillan approved these changes

2023-03-02 14:52 UTC, merged