initial check in
department-of-veterans-affairs/notification-api pull request #1113
Opened 2023-03-01 05:33 UTC by jakehova

# Description

Creating API code that will take a delivery status received from an external source via the ALB, parse it and determine the provider that sent the message and then package the message and enqueue it for processing by our ECS task.

#1074 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation changes only

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-06 15:09 UTC, cris-oddball approved these changes

2023-03-06 15:41 UTC, k-macmillan requested changes

2023-03-06 15:41 UTC, k-macmillan commented on lambda_functions/delivery_status_processor_lambda/delivery_status_processor_lambda.py
> +    logger.debug("SQS push data of type %s: %s", type(push_data), push_data)
Why do we need to specify the type?

2023-03-06 15:41 UTC, k-macmillan commented on lambda_functions/delivery_status_processor_lambda/delivery_status_processor_lambda.py
> +        if (encode):
```suggestion
        if encode:
```

2023-03-06 15:41 UTC, k-macmillan commented on lambda_functions/delivery_status_processor_lambda/delivery_status_processor_lambda.py
> +    except TypeError as e:
Are we certain we will only receive `TypeError` here? We have a lot going on in this try block.

2023-03-06 15:41 UTC, k-macmillan commented on lambda_functions/delivery_status_processor_lambda/delivery_status_processor_lambda.py
> +        logger.warning(". . . Completed the SQS push.")
```suggestion
        logger.info(". . . Completed the SQS push.")
```

2023-03-06 15:41 UTC, k-macmillan commented on tests/lambda_functions/delivery_status_processor_lambda/test_delivery_status_processor_lambda.py
> +    sqs_mock.assert_called_once()
event of `None` should raise. This does not check for that. In event: None or a full even it will call SQS.

2023-03-06 15:41 UTC, k-macmillan commented on tests/lambda_functions/delivery_status_processor_lambda/test_delivery_status_processor_lambda.py
> +    sqs_mock.assert_called_once()
Same, SQS check doesn't cover it.

2023-03-06 15:41 UTC, k-macmillan commented on tests/lambda_functions/delivery_status_processor_lambda/test_delivery_status_processor_lambda.py
> +    sqs_mock.assert_called_once()
Same.

2023-03-06 15:41 UTC, k-macmillan commented on tests/lambda_functions/delivery_status_processor_lambda/test_delivery_status_processor_lambda.py
> +    sqs_mock.assert_called_once()
Same.

2023-03-06 15:41 UTC, k-macmillan commented on tests/lambda_functions/delivery_status_processor_lambda/test_delivery_status_processor_lambda.py
> +    sqs_mock.assert_called_once()
Same.

2023-03-06 15:41 UTC, k-macmillan commented on tests/lambda_functions/delivery_status_processor_lambda/test_delivery_status_processor_lambda.py
> +    sqs_mock.assert_called_once()
Same.

2023-03-06 16:24 UTC, jakehova commented on lambda_functions/delivery_status_processor_lambda/delivery_status_processor_lambda.py
> +            "delivery_tag": str(uuid.uuid4())
I dont know enough about celery to say definitively what fields are necessary or not.  I kept everything from the existing methods that communicate with Celery.  I can do a deeper dive in Celery to whiddle this down.

2023-03-06 16:25 UTC, jakehova commented on lambda_functions/delivery_status_processor_lambda/delivery_status_processor_lambda.py
> +        "chord": None
Similar to above.  I dont know enough about Celery to definitively say whether eliminating this stuff is allowed or not.

2023-03-06 18:17 UTC, cris-oddball commented on lambda_functions/delivery_status_processor_lambda/delivery_status_processor_lambda.py
> +        logger.critical(f'Unknown Failure: {e}')
Logging should be %s not f-strings, correct? If so, please update.

2023-03-06 18:19 UTC, cris-oddball commented on lambda_functions/delivery_status_processor_lambda/delivery_status_processor_lambda.py
> +        logger.critical(". . . Failed to push to SQS with data: %s", push_data)
Looks like we need a newline here.

2023-03-06 18:19 UTC, cris-oddball commented on lambda_functions/delivery_status_processor_lambda/delivery_status_processor_lambda.py
> +        logger.critical(". . . Failed to push to SQS with data: %s", push_data)
Looks like we need a newline here.

2023-03-06 18:20 UTC, cris-oddball commented
Please add a label (enhancement?) and removed unused lines in the description. Or check them off if applicable.

2023-03-06 19:40 UTC, k-macmillan requested changes

2023-03-06 19:40 UTC, k-macmillan commented on lambda_functions/delivery_status_processor_lambda/delivery_status_processor_lambda.py
> +    if (push_data is None):
```suggestion
    if push_data is None:
```

2023-03-06 19:40 UTC, k-macmillan commented on tests/lambda_functions/delivery_status_processor_lambda/test_delivery_status_processor_lambda.py
> +    assert valid_event(event) == True
```suggestion
    assert valid_event(event)
```
`valid_event()` returns a boolean `True` on valid events, no need for the extra check.

2023-03-06 19:41 UTC, k-macmillan requested changes

2023-03-06 19:41 UTC, k-macmillan commented on lambda_functions/delivery_status_processor_lambda/delivery_status_processor_lambda.py
> +if (DELIVERY_STATUS_RESULT_TASK_QUEUE is None):
```suggestion
if DELIVERY_STATUS_RESULT_TASK_QUEUE is None:
```

2023-03-06 19:41 UTC, k-macmillan commented on lambda_functions/delivery_status_processor_lambda/delivery_status_processor_lambda.py
> +if (DELIVERY_STATUS_RESULT_TASK_QUEUE_DEAD_LETTER is None):
```suggestion
if DELIVERY_STATUS_RESULT_TASK_QUEUE_DEAD_LETTER is None:
```

2023-03-07 17:47 UTC, cris-oddball submitted a review, later dismissed

2023-03-07 18:43 UTC, k-macmillan requested changes
I ran a pep8 formatter and there were a bunch of changes between the two .py files. Please run a formatter over these two and fix the extra imports.

2023-03-07 18:43 UTC, k-macmillan commented on tests/lambda_functions/delivery_status_processor_lambda/test_delivery_status_processor_lambda.py
> +import json
Remove unused imports.

2023-03-07 19:03 UTC, cris-oddball approved these changes

2023-03-07 21:27 UTC, k-macmillan commented
Tested in the lambda console with the json from the engineering spike ticket. 
Test:
![image](https://user-images.githubusercontent.com/16893311/223556770-9061704a-b346-4b6b-9319-bfc45bdc4e8a.png)


Result showing in the log:
![image](https://user-images.githubusercontent.com/16893311/223556664-7a4fbfeb-7d19-4815-bc09-be2612187fd5.png)

2023-03-07 21:28 UTC, k-macmillan approved these changes

2023-03-07 22:00 UTC, jakehova commented
Tested Twilio to ALB to Lambda AND Lambda directly.  All tests passed.

2023-03-15 18:24 UTC, k-macmillan commented
This was supposed to be merged but slipped the through the cracks. Will merge after updating with master.

2023-03-15 18:35 UTC, merged