939 ve text 502
department-of-veterans-affairs/notification-api pull request #1117
Opened 2023-03-08 14:37 UTC by jakehova

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation changes only

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-14 17:24 UTC, k-macmillan approved these changes

2023-03-14 20:22 UTC, k-macmillan requested changes

2023-03-14 20:22 UTC, k-macmillan commented on tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py
> +        {}, 200, '<?xml version="1.0" encoding="UTF-8"?><Response></Response>'
I believe this needs to be changed now.

2023-03-15 22:12 UTC, k-macmillan commented on tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py
> +        {}, 200, '<?xml version="1.0" encoding="UTF-8"?><Response></Response>'
This appears to be for the post to vetext, not our response to Twilio.

2023-03-15 22:12 UTC, k-macmillan submitted a review, later dismissed

2023-03-15 22:19 UTC, k-macmillan commented
Master merge involved github actions and delivery status work. None of that applies to this lambda.

2023-03-15 22:34 UTC, k-macmillan approved these changes
I did not change any of this code. No conflict of interest.

2023-03-16 11:21 UTC, ldraney approved these changes

2023-03-16 13:42 UTC, merged