#1194 Add missing unit test for twilio
department-of-veterans-affairs/notification-api pull request #1197
Opened 2023-04-04 14:36 UTC by justaskdavidb2

# Description

These changes add and update unit test for the Twilio callback task.  One test, marked xfail, uncovered a bug to be addressed by #1217.

#1194 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- [x] All Unit Test Pass (except 1 new xfail)
- [x] [deployed](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/4690801306)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes (except 1 xfail)
- [x] Any dependent changes have been merged and published in downstream modules

## Additional Info & Resources
Uncovered related issue: #1217

2023-04-11 17:41 UTC, kalbfled commented on tests/app/celery/test_process_delivery_status_result_tasks.py
> +# here we make a fake Celery Task to support the use of self
Please make this a class docstring rather than a regular comment.

2023-04-11 18:36 UTC, kalbfled commented on tests/app/celery/test_process_delivery_status_result_tasks.py
> +# confirmed: task should retry when incoming message does not contain a message attribute
delete

2023-04-11 21:24 UTC, kalbfled requested changes
Please make the relevant changes wherever they are applicable; not just where I commented.

2023-04-11 21:24 UTC, kalbfled commented on tests/app/celery/test_process_delivery_status_result_tasks.py
> +    assert provider_name == provider_name_output == provider.name
Hmm.  At a minimum, this is inconsistent with Pep8.  Scroll up from [here](https://pep8.org/#function-annotations).

If `provider_name == provider_name_output` is true, this becomes an assertion that `True == provider.name`.

2023-04-11 21:24 UTC, kalbfled commented on tests/app/celery/test_process_delivery_status_result_tasks.py
> +    reference = 'SMyyy'
unused (but should be)

2023-04-11 21:24 UTC, kalbfled commented on tests/app/celery/test_process_delivery_status_result_tasks.py
> +    reference = 'SMyyy'
ditto

2023-04-11 21:24 UTC, kalbfled commented on tests/app/celery/test_process_delivery_status_result_tasks.py
>          "app.celery.process_delivery_status_result_tasks.attempt_to_get_notification",
How does this need to be mocked?

2023-04-11 21:24 UTC, kalbfled commented on tests/app/celery/test_process_delivery_status_result_tasks.py
> +    )
How does this need a mock?

2023-04-12 14:31 UTC, cris-oddball requested changes
In general, comments should be de-personalized. Rather than "here we attempt to get the foobar" instead write "get the foobar."

Or instead of "We want to test that attempt_to_get_notification triggers a celery Retry when notification is None" use "validate that attempt_to_get_notification triggers a celery Retry if notification is None"

Ideally, if methods, tests, variables and constants are well named, then comments are unneeded.

If the comment explains what is clearly written in the code, then the comment itself is superfluous.

2023-04-12 14:31 UTC, cris-oddball commented on tests/app/celery/test_process_delivery_status_result_tasks.py
> +# todo: make sure this is still true
Any TODO in the code should include any ticket necessary to fix it in the future, unless you plan on doing this in this PR, but at a later date, in which case you might make a note of it. Also, TODO needs to capitalized, which IDEs usually render in a different color or just list out all the TODOs for you.

2023-04-12 14:31 UTC, cris-oddball commented on tests/app/celery/test_process_delivery_status_result_tasks.py
> +# todo: make sure this is still true
Also, the confirmed comment should be deleted.

2023-04-12 14:31 UTC, cris-oddball commented on tests/app/celery/test_process_delivery_status_result_tasks.py
> +# here we test all valid provider names
are you planning to add more provider names? there is no need to parameterize if you aren't.

2023-04-12 14:31 UTC, cris-oddball commented on tests/app/celery/test_process_delivery_status_result_tasks.py
>      """verify that retry is triggered if translate_delivery_status is returns a None"""
grammar?

2023-04-12 14:42 UTC, kalbfled commented on tests/app/celery/test_process_delivery_status_result_tasks.py
> +    # todo: a way to confirm that check_and_queue_callback_task() was called
I concur.  In my text editor (gEdit), TODO shows up in a different color than "todo".

2023-04-12 23:12 UTC, cris-oddball requested changes
Please add a label to this PR (like, bug). Otherwise, LGTM.

2023-04-13 14:12 UTC, kalbfled commented
> Please add a label to this PR (like, bug). Otherwise, LGTM.

I added the "bug" label.

2023-04-13 14:26 UTC, cris-oddball approved these changes

2023-04-13 14:31 UTC, jakehova approved these changes

2023-04-13 15:21 UTC, merged