#1294 process delivery status appears to enter final state then exit it
department-of-veterans-affairs/notification-api pull request #1310
Opened 2023-06-06 15:41 UTC by babyjunior56

# Description

The process delivery status task must provide the current notification.status when attempting to update the status of the notification in the database.

For all notifications in the database, a notification status cannot be:

- set to "sent" after being set to "delivered"
- set to "sending" after being set to "sent"

Test cases were created that :

- test for new logic for process delivery status
- test for checking for new notification
- test include legacy code for updating delivery status

#1294

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [x] The unit test cases for testing if notifications can go from sent->sending and delivered->sending passed validation
- [x] The unit test cases for applying conditional "new status" value in the processing of callbacks passed validation
- [x] All already existing Test Cases pass
- [x] In the dev environment: Confirm that postman will send text messages notifications
- [x] In the dev environment: The process delivery status callback produced the expected log messages in cloudwatch
- [x] In the dev environment: confirmed that process delivery task callback receives response message from twilio and able to complete.
- [x] In the dev environment: confirmed receipt of email
- [x] In the dev environment: confirmed that appropriate log messages were for found for twilio, pinpoint, and email.
- [x] In the dev environment: confirmed that test case all pass in dev
- [x] email screenshots to QA

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-06-06 19:51 UTC, cris-oddball requested changes
Please handle the failing test on the flask dependency with an exclusion until we work that ticket.

2023-06-06 22:23 UTC, cris-oddball commented on Makefile
> +    .DEFAULT_GOAL := help
Why the tab/spaces here?

2023-06-07 19:31 UTC, kalbfled requested changes

2023-06-07 19:31 UTC, kalbfled commented on app/dao/notifications_dao.py
> +    order_matrix = [NOTIFICATION_SENDING, NOTIFICATION_SENT, NOTIFICATION_DELIVERED]
Tuple; not list.  Please refer to my comment below.

2023-06-07 19:31 UTC, kalbfled commented on app/dao/notifications_dao.py
> +        notification.filter(Notification.status == current_status)
"notification" is a misleading variable name here.  At a glance, one might assume it is a Notification instance, but it's actually a query instance.  I would call it "notification_query".

2023-06-07 19:31 UTC, kalbfled commented on app/dao/notifications_dao.py
> +        )
@k-macmillan Do we need to log this?  It seems like something that will happen frequently.

2023-06-07 19:31 UTC, kalbfled commented on app/dao/notifications_dao.py
> +            )
@k-macmillan Ditto.

2023-06-07 21:08 UTC, cris-oddball requested changes

2023-06-07 21:08 UTC, cris-oddball commented on app/celery/process_delivery_status_result_tasks.py
> -
Why are we removing this as a hidden method? I get that it's only used in this file, but I don't get what that has to do with the ticket itself.

2023-06-08 18:01 UTC, cris-oddball commented
Confirmed that code works in the Perf environment as expected.

2023-06-08 18:03 UTC, cris-oddball commented on tests/app/dao/notification_dao/test_notification_dao.py
@kalbfled given the very short runway we have to get this code out, are these test cases changes necessary? If you really believe that the tests need to change, that's OK, but if we can defer this to a secondary ticket so that we can get this code out the door, let's do that please by dismissing your review in favor of a follow-on ticket just for the tests.

2023-06-08 18:10 UTC, kalbfled commented on tests/app/dao/notification_dao/test_notification_dao.py
I'm fine with the tests as written as long as they pass.

2023-06-08 18:23 UTC, kalbfled approved these changes
I'm approving this as written with the understanding that @justaskdavidb2 is opening a tech debt issue to make the unit tests more concise.

2023-06-08 18:29 UTC, merged