#1268 Updated the OpenAPI specification and Postman collection for CommunicationItem
department-of-veterans-affairs/notification-api pull request #1317
Opened 2023-06-13 20:56 UTC by kalbfled

# Description

These changes:
1. Add all CommunicationItem routes to [our OpenAPI specification](https://github.com/department-of-veterans-affairs/notification-api/tree/master/documents/openapi)
2. Make a minor tweak to a default request body in the Postman collection that I should have made for #1253
3. Use `nullable: false` to create documentation that shows up in the Swagger Editor.  `nullable` isn't part of the OpenAPI or JSON Schema specifications, but our specification uses it extensively.

These changes do not make any updates to [openapi-with-push.yaml](https://github.com/department-of-veterans-affairs/notification-api/blob/master/documents/openapi/openapi-with-push.yaml), which is not discussed in README.md and does not seem to be in use.

Useful documentation and tools:
1. [OpenAPI specification](https://spec.openapis.org/oas/latest.html)
2. [Understanding JSON Schema](https://json-schema.org/understanding-json-schema/)
4. [Swagger Editor](https://editor-next.swagger.io/)

#1268

## Type of change

- [x] Documentation changes only

## How Has This Been Tested?

- [x] Verified that everything looks correct in [Swagger Editor](https://editor-next.swagger.io/) by opening [this URL](https://raw.githubusercontent.com/department-of-veterans-affairs/notification-api/1268-api-docs/documents/openapi/openapi.yaml)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

2023-06-13 21:26 UTC, cris-oddball requested changes
Just a few things... otherwise looks great!

- increment the version on line 4 to 1.0.2
- Order the routes so that they appear in the UI in this order:
  - GET ALL
  - GET by ID
  - POST
  - PATCH
  - DEL

2023-06-13 22:26 UTC, ldraney approved these changes

2023-06-14 14:22 UTC, kalbfled commented
>     * increment the version on line 4 to 1.0.2

Done.

>     * Order the routes so that they appear in the UI in this order:
>       
>       * GET ALL
>       * GET by ID
>       * POST
>       * PATCH
>       * DEL

GET ALL and POST use the route `/communication_item`, and the remaining endpoints use `/communication_item/{communication_item_id}`.  I would have to duplicate [path objects](https://spec.openapis.org/oas/latest.html#pathsObject) to get the above order, and no other endpoint in the file does that.  They are first ordered by endpoint and then by HTTP method.

For the latter endpoint, I moved DELETE to the end, and this is consistent with the rest of the file.  Consider "callback", for example.

2023-06-14 15:02 UTC, ldraney approved these changes

2023-06-14 15:58 UTC, merged