#1241 June Routine upgrades
department-of-veterans-affairs/notification-api pull request #1325
Opened 2023-06-19 05:45 UTC by justaskdavidb2

# Description

Added latest updates for python modules that will not cause failed tests

#1241

## Type of change

Please delete options that are not relevant.

-  New feature (non-breaking change which adds functionality) --> upgrades only

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Local Test Cases pass
- [x] All Unit Test Cases pass
- [x] Made sure DataDog received data from AWS
- [x] Twilio can send messages
- [x] Cloudwatch logs for errors

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-06-20 13:46 UTC, cris-oddball requested changes

2023-06-20 13:46 UTC, cris-oddball commented on requirements.txt
> +requests==2.31.0
I thought we couldn't upgrade requests due to the alpine container version? Was this code deployed to Dev?

2023-06-20 13:46 UTC, cris-oddball commented on requirements.txt
> +urllib3==1.26.16
I thought we also couldn't upgrade urllib3 due to the alpine container version - was this code deployed to dev?

2023-06-20 18:30 UTC, kalbfled requested changes
Do these changes clear any vulnerabilities identified by Safety?  I'm pretty sure they do.  I would expect additional changes in Makefile to remove currently ignored vulnerabilities.

Please also note that this branch needs to be rebased to master.  I think that's why the CodeQL check says, "configuration not found."  That workflow is running from master, but your branch doesn't have the relevant files.

2023-06-21 18:45 UTC, cris-oddball requested changes

2023-06-21 18:45 UTC, cris-oddball commented on requirements-app.txt
> +# Cannot upgrade because of breaking changes causing "Attribute Error: 'Cookie' has no attribute 'name'"
With the update, you now have duplicate text on line 30, line 31. At this point, just delete the comments on lines 29 and 30, the comments on 31 and 32 suffice.

2023-06-21 19:14 UTC, cris-oddball approved these changes

2023-06-21 19:20 UTC, kalbfled approved these changes

2023-06-21 20:04 UTC, merged