#1348 Release Trigger Action Bug fix
department-of-veterans-affairs/notification-api pull request #1349
Opened 2023-06-29 20:01 UTC by ldraney

# Description

The Release Trigger action fails to initiate a deploy to Prod when a Release is Published.
This also adds a syntax improvement to improve reliability. 
Addresses #1348

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- [ ] The POC video can be [found here](https://drive.google.com/file/d/1zX7HTm15SH843abo3sZ9vupsrpJdsfhO/view?usp=sharing)
- [ ] The POC documnet that includes that shows the same code structure working in a test repo can be [found here](https://docs.google.com/document/d/1GjB-77RT1odUZC8TumpTK0pLKJJ7TxHZJh0vIb3BpFY/edit)

## Checklist
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

2023-06-29 20:08 UTC, cris-oddball requested changes
please rename `.github/workflows/pre-release_trigger.yml` to `.github/workflows/prerelease_trigger.yml` without mixing dashes and underscores.

2023-06-29 20:08 UTC, cris-oddball commented on .github/workflows/pre-release_trigger.yml
> +    secrets: inherit
why is this still needed here? this workflow should only be for the pre-release.

2023-06-29 20:08 UTC, cris-oddball commented on .github/workflows/release_trigger.yml
> +          echo "is published (staging) or a release (prod)?: ${{ github.event.action }}"
Why is staging in here?

2023-06-29 20:08 UTC, cris-oddball commented on .github/workflows/release_trigger.yml
>        environment: "staging"
why is a pre-release needed here?

2023-06-29 20:15 UTC, ldraney commented on .github/workflows/release_trigger.yml
> +          echo "is published (staging) or a release (prod)?: ${{ github.event.action }}"
Simply as a string check to be sure

2023-06-29 20:26 UTC, ldraney commented on .github/workflows/release_trigger.yml
>        environment: "staging"
removed

2023-06-30 14:18 UTC, cris-oddball submitted a review, later dismissed

2023-06-30 15:07 UTC, cris-oddball approved these changes

2023-06-30 15:43 UTC, kalbfled approved these changes

2023-06-30 15:45 UTC, merged