Update PR Template
department-of-veterans-affairs/notification-api pull request #1435
Opened 2023-08-29 15:48 UTC by ldraney

# Description

This PR updates our current PR template to better align with our revised "Definition of Mergeable". As discussed, I've incorporated checkboxes that reflect our criteria for what makes a PR mergeable. This will help ensure that all contributors adhere to our standards and make our review process more streamlined.

[The link to our definition of mergeable](https://docs.google.com/document/d/1nwZIF_lydPWfvixxZlQLNt4nqy3Qp13pHQnMcYJjTqE/edit#heading=h.6mnhaqm79e12)

## Type of change

- [x] Documentation changes only

## How Has This Been Tested?

This change doesn't require traditional testing since it's a documentation update. However, I've previewed the markdown and ensured that the format appears correctly on GitHub.

2023-08-29 16:09 UTC, cris-oddball approved these changes
You'll need to override the certifi issue to merge this. Check with Dave to see if he plans to handle that on his PR or if we need a PR just for that issue.

2023-08-30 20:00 UTC, cris-oddball requested changes

2023-08-30 20:00 UTC, cris-oddball commented on .github/pull_request_template.md
> +Fixes # (issue)
This will end up closing the ticket. Sometimes we don't want the ticket closed so that QA can approve it. Please change to (issue)

2023-08-30 22:14 UTC, nikolai-efimov requested changes

2023-08-30 22:14 UTC, nikolai-efimov commented on .github/pull_request_template.md
> +- [ ] Test B
I’d suggest
- [ ] e.g. Unit tested locally
- [ ] e.g. Unit tested on GitHub

2023-09-01 18:09 UTC, cris-oddball approved these changes

2023-09-01 18:25 UTC, merged