#1360 POST /v3/notifications/ revision 1
department-of-veterans-affairs/notification-api pull request #1438
Opened 2023-09-05 21:39 UTC by kalbfled

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

issue #1360

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation changes only

## How Has This Been Tested?

How has this been tested? (e.g., screenshots, links to deployment, regression test results) to demonstrate the functionality or fix: e.g. Tested locally, Tested as a GitHub action, etc.

## Checklist

- [ ] I have assigned myself to this PR
- [ ] PR has an appropriate title: #9999 - What the thing does
- [ ] PR has a detailed description, including links to specific documentation
- [ ] I have added the [appropriate labels](https://github.com/department-of-veterans-affairs/notification-api/blob/master/.github/release.yaml) to the PR.
- [ ] I did not remove any parts of the template, such as checkboxes even if they are not used
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to any documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have ensured the latest master is merged into my branch and all checks are green prior to review
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] The ticket is now moved into the DEV test column

2023-09-05 22:12 UTC, kalbfled commented on app/v3/notifications/rest.py
> +        return {"id": v3_send_notification(request_data)}, 202
This user data is validated against a schema.

2023-09-05 23:01 UTC, cris-oddball requested changes
Note sure what file to comment upon here, but if i send an sms or an email without a recipient_id or a phone_number/email_address, the response is
```
{
    "errors": [
        {
            "error": "ValidationError",
            "message": "{'template_id': 'd6cba13a-239c-41ce-81e1-9bd1e95973c2', 'notification_type': 'sms'} is not valid under any of the given schemas"
        }
    ]
}
```
That is not a useful message.  The message should state something like "Please provide either a phone number or recipient identifier." which is what the v2 routes return in that situation.

2023-09-05 23:04 UTC, cris-oddball commented
For some reason, now getting a lot of these errors in DEV, hard to say if this is related to these code changes. 
```
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='dev-api.va.gov', port=443): Read timed out. (read timeout=30)
```

Time now is 5:03 PM MT, perhaps a search of the logs on Dev at this time can reveal what the problem is.

2023-09-05 23:14 UTC, cris-oddball commented
Also, please do run the QA Suite after deploying to Dev - that is not in your 'How Has This Been Tested?' section and since the QA Suite effectively replaces User Flows, it _should_ be run on every deploy.

**The regression does pass on DEV (only v2 routes are tested)**: `134 passed, 3 xfailed in 207.60s (0:03:27)`

BUT my branch that has tests for v3 (which were working earlier today) now have randomly failing errors on the **v3** routes
```
E           urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='dev-api.va.gov', port=443): Read timed out. (read timeout=30)

```

By random, I mean that sometimes a test fails with that read timed out error, another time it passes, different tests failing each run.

2023-09-06 14:38 UTC, kalbfled commented on documents/openapi/openapi.yaml
> +          $ref: "#/components/responses/Unauthorized_401_V3"
I added client_reference and made some other improvements.  scheduled_for is not part of v3.

2023-09-06 19:03 UTC, kalbfled commented on app/v3/notifications/rest.py
> +        raise RuntimeError("Unrecognized notification type.  This is a programming error.")
That's intentional.

2023-09-06 19:05 UTC, EvanParish commented on app/v3/notifications/rest.py
> +        raise RuntimeError("Unrecognized notification type.  This is a programming error.")
okay, then disregard. What is the reason though? Just curious. Is it to just differentiate it in the logs or something?

2023-09-06 20:33 UTC, cris-oddball commented
Please remove all labels except enhancement from this PR, please. The labels are meant to place the PR in a certain spot on the releases, so just one is needed. There also is no QA label and this is a new feature so it is not a bug or dependency.

2023-09-06 23:19 UTC, kalbfled commented on app/v3/notifications/rest.py
> +        return {"id": v3_send_notification(request_data)}, 202
This user data is validated against a schema.

2023-09-06 23:22 UTC, kalbfled commented on tests/app/v3/notifications/test_rest.py
> +                "phone_number": "+18006982411",
This is an actual VA phone number that is "valid" according to phonenumbers.

2023-09-06 23:48 UTC, cris-oddball approved these changes

2023-09-07 14:27 UTC, EvanParish approved these changes

2023-09-07 14:58 UTC, EvanParish approved these changes

2023-09-07 14:58 UTC, cris-oddball approved these changes

2023-09-07 15:01 UTC, merged