#1178 remove letter and pdf
department-of-veterans-affairs/notification-api pull request #1460
Opened 2023-09-21 19:21 UTC by babyjunior56

# Description

Removed all code that used:
Celery tasks - app/celery/letters_pdf_tasks.py
Removed all code that required the creation or uploading  letters
Removed all code that required the pdf endpoint
Removed all code that required the letters endpont
Removed unused variables
   

issue #1178 

## Type of change

Please check the relevant option(s).

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation changes only

## How Has This Been Tested?
- [x] Ran Unit test locally
- [x] Deployed to Dev 

## Checklist

- [x] I have assigned myself to this PR
- [x] PR has an appropriate title: #9999 - What the thing does
- [x] PR has a detailed description, including links to specific documentation
- [x] I have added the [appropriate labels](https://github.com/department-of-veterans-affairs/notification-api/blob/master/.github/release.yaml) to the PR.
- [x] I did not remove any parts of the template, such as checkboxes even if they are not used
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to any documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have ensured the latest master is merged into my branch and all checks are green prior to review
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] The ticket is now moved into the DEV test column

2023-09-21 19:28 UTC, kalbfled requested changes
You have not deleted [this](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/v2/notifications/get_notifications.py#L30) route.

2023-09-28 19:37 UTC, cris-oddball requested changes
Seems like there are still a lot of letters related items that in these files?

2023-09-28 19:37 UTC, cris-oddball commented on app/celery/tasks.py
>  from app.dao.daily_sorted_letter_dao import dao_create_or_update_daily_sorted_letter
Shouldn't this import be removed? `dao_create_or_update_daily_sorted_letter`

2023-09-28 19:37 UTC, cris-oddball commented on app/celery/tasks.py
>  from app.dao.daily_sorted_letter_dao import dao_create_or_update_daily_sorted_letter
It's used once later in this file starting at line 460 in `def persist_daily_sorted_letter_counts()` - shouldn't that also be removed?

2023-09-28 19:37 UTC, cris-oddball commented on app/celery/tasks.py
>  from app.dao.daily_sorted_letter_dao import dao_create_or_update_daily_sorted_letter
There are in fact other letters methods in this file - why are we keeping those?

2023-09-28 19:37 UTC, cris-oddball commented on app/v2/notifications/post_notifications.py
>      UPLOAD_DOCUMENT,
Why are we importing these?

2023-09-28 19:37 UTC, cris-oddball commented on app/v2/notifications/post_notifications.py
>      post_letter_request,
why are we importing this?

2023-09-28 19:37 UTC, cris-oddball commented on tests/app/v2/notifications/test_post_notifications.py
>              service_with_upload_document_permission,
is this used?

2023-09-29 19:24 UTC, closed without merging