More Swagger corrections
department-of-veterans-affairs/notification-api pull request #1468
Opened 2023-09-28 21:11 UTC by kalbfled

# Description

These changes eliminate console errors (bottom left) visible when loading our openapi.yml file into the [newer Swagger Editor](https://editor-next.swagger.io/).  These problems are all improper use of the "items" attribute for data that is not an array.  I changed the spec to reflect what Flask is actually doing.

A different error is displayed in the top right if you load the file into the [older Swagger Editor](https://editor.swagger.io/).  According to the Json schema docs, "const" can be used for attribute, and it doesn't request also specifying "type".  I removed the "type" specifier thinking that was the problem in the older editor, but it didn't fix it.  I'm thinking the older editor is just wrong.

There is no associated ticket.

## Type of change

Please check the relevant option(s).

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation changes only

## How Has This Been Tested?

I loaded the file and the older and newer Swagger editor.

## Checklist

- [x] I have assigned myself to this PR
- [x] PR has an appropriate title: #9999 - What the thing does
- [x] PR has a detailed description, including links to specific documentation
- [x] I have added the [appropriate labels](https://github.com/department-of-veterans-affairs/notification-api/blob/master/.github/release.yaml) to the PR.
- [x] I did not remove any parts of the template, such as checkboxes even if they are not used
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to any documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have ensured the latest master is merged into my branch and all checks are green prior to review
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] The ticket is now moved into the DEV test column

2023-09-28 21:14 UTC, cris-oddball requested changes
Can you please increment the version on line 4 of the file? 
I meant to advise you of this the last time I reviewed swagger but forgot to do so!

2023-09-28 21:27 UTC, kalbfled commented
> Can you please increment the version on line 4 of the file? I meant to advise you of this the last time I reviewed swagger but forgot to do so!

Done.

2023-09-29 14:01 UTC, cris-oddball approved these changes
Well done job in getting rid of the errors!

2023-09-29 14:27 UTC, k-macmillan approved these changes

2023-09-29 14:27 UTC, EvanParish approved these changes

2023-09-29 14:33 UTC, merged