#1727 CD Pipeline Tag Versioning
department-of-veterans-affairs/notification-api pull request #1733
Opened 2024-04-16 16:53 UTC by ldraney

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

The goal of this PR is to automate tagging as a part of our release process. 

The values from the initial PR merge to master will be saved in the workflow; and once it has been merged to the release branch, those labels with be the basis for the tag version that is created on the release branch. 

issue #1727 

## Type of change

Please check the relevant option(s).

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation changes only

## How Has This Been Tested?

How has this been tested? (e.g. Unit tests, Tested locally, Tested as a GitHub action, Depoyed to dev, etc)  
Please provide relevant information and / or links to demonstrate the functionality or fix. (e.g. screenshots, link to deployment, regression test results, etc)

## Checklist

- [ ] I have assigned myself to this PR
- [ ] PR has an appropriate title: #9999 - What the thing does
- [ ] PR has a detailed description, including links to specific documentation
- [ ] I have added the [appropriate labels](https://github.com/department-of-veterans-affairs/notification-api/blob/master/.github/release.yaml) to the PR.
- [ ] I did not remove any parts of the template, such as checkboxes even if they are not used
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to any documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have ensured the latest master is merged into my branch and all checks are green prior to review
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] The ticket is now moved into the DEV test column

2024-05-06 22:07 UTC, cris-oddball requested changes
please delete all of your non-v tags and reset whatever is stored so that we start from a fresj slate when this PR is merged.

2024-05-07 15:10 UTC, cris-oddball approved these changes

2024-05-07 21:24 UTC, kalbfled requested changes

2024-05-07 21:24 UTC, kalbfled commented on .github/scripts/prData.js
> +    }));
Test this to be certain, but I think this is a no-op that can be deleted.  The "map" return value is identical to the input.  The output, "labels", is just a copy of "const labels = pullRequestData.data[0].labels".  You could just do this . . .

```
const labels = pullRequestData.data[0].labels
```

. . . or not even have a new variable.

One reason to make a copy is that downstream code modifies the values, and you don't want to change the original values.  In this case, there's probably a more concise way to make a copy.

2024-05-07 21:24 UTC, kalbfled commented on .github/scripts/prData.js
> +    labels.some((label) => ["hotfix", "security", "bug"].includes(label.name))
Please comment that this is the "patch" case.

2024-05-07 21:24 UTC, kalbfled commented on .github/scripts/prData.js
> +  if (labels.some((label) => label.name === "breaking-change")) {
Please comment that this is the "major" case.

2024-05-07 21:24 UTC, kalbfled commented on .github/scripts/prData.js
> +  } else {
Please comment that this is the "minor" case.

2024-05-07 21:24 UTC, kalbfled commented on .github/scripts/prData.js
> +    appliedLabel = labels.find((label) => label).name; // Catch-all increment
Isn't this just taking the first label in the list?  If that's the case, there's no need to "find".

2024-05-08 21:24 UTC, kalbfled commented on .github/scripts/prData.js
> + * @returns {Object|null} - An object containing pull request processing results or null in case of error.
will return a promise because it's async

2024-05-08 21:26 UTC, kalbfled commented on .github/scripts/prLabelSemver.js
> +const fs = require("fs");
Unused import.  Please check this for all files.

2024-05-08 21:27 UTC, kalbfled commented on .github/scripts/prLabelSemver.js
> +const prLabelSemver = async ({ github, context, core }) => {
You're still using lambda syntax here, and the return value should be a promise.

2024-05-08 21:28 UTC, kalbfled commented on .github/scripts/preTagSummary.js
> +const fs = require("fs");
unused import

2024-05-08 21:28 UTC, kalbfled commented on .github/scripts/preTagSummary.js
> +const preTagSummary = async ({ github, context, core }) => {
lambda syntax

2024-05-08 21:28 UTC, kalbfled commented on .github/scripts/preTagSummary.js
> + * @param {object} core - The GitHub core library, used for setting action failure messages.
returns a promise

2024-05-08 21:30 UTC, kalbfled commented on .github/workflows/create-and-post-tag.yml
> +      - 1727-cd-pipeline-versioning
Is this for testing?  Wasn't it "master" before?  Ditto elsewhere.

2024-05-08 22:05 UTC, kalbfled requested changes

2024-05-08 22:05 UTC, kalbfled commented on .github/scripts/prLabelSemver.js
>   */
Return type?  You included that elsewhere.

2024-05-08 22:11 UTC, kalbfled submitted a review, later dismissed

2024-05-08 22:15 UTC, kalbfled submitted a review, later dismissed

2024-05-09 13:41 UTC, cris-oddball requested changes

2024-05-09 13:41 UTC, cris-oddball commented on .github/scripts/actionUtils.js
> +// tagSummaryUtils.js
If this is supposed to be the file's name, it is not, Please adjust either this line to match the filename or update the filename and anywhere else it is called.

2024-05-09 13:44 UTC, cris-oddball approved these changes

2024-05-09 14:07 UTC, kalbfled approved these changes

2024-05-09 14:21 UTC, merged