UTILS-146 - Remove comment regarding 146
department-of-veterans-affairs/notification-api pull request #1844
Opened 2024-06-27 02:38 UTC by MackHalliday

1. 

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

issue #(issue)

## Type of change

Please check the relevant option(s).

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation changes only

## How Has This Been Tested?

How has this been tested? (e.g. Unit tests, Tested locally, Tested as a GitHub action, Depoyed to dev, etc)  
Please provide relevant information and / or links to demonstrate the functionality or fix. (e.g. screenshots, link to deployment, regression test results, etc)

## Checklist

- [ ] I have assigned myself to this PR
- [ ] PR has an appropriate title: #9999 - What the thing does
- [ ] PR has a detailed description, including links to specific documentation
- [ ] I have added the [appropriate labels](https://github.com/department-of-veterans-affairs/notification-api/blob/master/.github/release.yaml) to the PR.
- [ ] I did not remove any parts of the template, such as checkboxes even if they are not used
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to any documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have ensured the latest master is merged into my branch and all checks are green prior to review
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] The ticket is now moved into the DEV test column

2024-06-27 19:10 UTC, kalbfled submitted a review, later dismissed

2024-06-27 20:02 UTC, k-macmillan approved these changes

2024-06-27 20:47 UTC, cris-oddball requested changes
There should be testing here, because we need to know that the API picked up the Utils change. If you deployed this out to Dev and the regression passed, there should be evidence of the debug logs, so please provide that evidence.

2024-06-27 21:52 UTC, EvanParish approved these changes

2024-06-27 21:55 UTC, EvanParish commented
> There should be testing here, because we need to know that the API picked up the Utils change. If you deployed this out to Dev and the regression passed, there should be evidence of the debug logs, so please provide that evidence.

There should at least be the mention of it being tested on the [utils pr](https://github.com/department-of-veterans-affairs/notification-utils/pull/155), but I approved because I saw the testing done there.

2024-06-28 14:06 UTC, cris-oddball approved these changes

2024-06-28 14:06 UTC, merged