#2013 - Add callback_url field to Notification table
department-of-veterans-affairs/notification-api pull request #2028
Opened 2024-10-01 20:36 UTC by MackHalliday

# Description

- Adding a `callback_url` column to the Notification table with upgrade and downgrade

issue #2013 

## How Has This Been Tested?

### [Deploy to Dev OK](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/11132430986)
Screenshot from DEV DB - Notification Table 
<img width="992" alt="Screenshot 2024-10-01 at 4 14 27 PM" src="https://github.com/user-attachments/assets/26f3f3f5-c3ec-4a56-93a1-f1737e131bd6">

### [Downgrade in DEV OK ](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/11132895612)
Screenshot from DEV DB  AFTER Downgrade - Notification Table 
<img width="1079" alt="Screenshot 2024-10-01 at 4 27 06 PM" src="https://github.com/user-attachments/assets/fd9eefc7-26e3-4f1e-9d68-41809902ffcc">

## Checklist

- [x] I have assigned myself to this PR
- [x] PR has an [appropriate title](https://github.com/department-of-veterans-affairs/vanotify-team/blob/main/Engineering/team_agreement.md#naming-prs): #9999 - What the thing does
- [x] PR has a detailed description, including links to specific documentation
- [x] I have added the [appropriate labels](https://github.com/department-of-veterans-affairs/vanotify-team/blob/main/Engineering/pull_request_labels.md#vanotify-labels) to the PR.
- [x] I did not remove any parts of the template, such as checkboxes even if they are not used
- [x] My code follows the [style guidelines](https://github.com/department-of-veterans-affairs/vanotify-team/blob/main/Process/style_guide.md) of this project
- [x] I have performed a self-review of my own code
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to any documentation
- [x] My changes generate no new warnings
- [n/a] I have added tests that prove my fix is effective or that my feature works. [Testing guidelines](https://github.com/department-of-veterans-affairs/vanotify-team/blob/main/Process/testing_guide.md)
- [x] I have ensured the latest main is merged into my branch and all checks are green prior to review
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] The ticket was moved into the DEV test column when I began testing this change

2024-10-01 21:39 UTC, cris-oddball requested changes
Please include the testing info fro this AC, "Ensure downgrade works even if the table has data in the new column"

2024-10-02 15:29 UTC, k-macmillan requested changes

2024-10-02 15:29 UTC, k-macmillan commented on migrations/versions/0370_notification_callback_url.py
> +revision = '5deab283266f'
This revision should follow previous formats. Please adjust it.

2024-10-02 17:50 UTC, EvanParish approved these changes

2024-10-02 17:51 UTC, merged