#2079 SMS Content Length StatsD Metric
department-of-veterans-affairs/notification-api pull request #2139
Opened 2024-11-20 18:06 UTC by mchlwellman

# Description

issue #(issue)

## How Has This Been Tested?

## Checklist

- [ ] I have assigned myself to this PR
- [ ] PR has an [appropriate title](https://github.com/department-of-veterans-affairs/vanotify-team/blob/main/Engineering/team_agreement.md#naming-prs): #9999 - What the thing does
- [ ] PR has a detailed description, including links to specific documentation
- [ ] I have added the [appropriate labels](https://github.com/department-of-veterans-affairs/vanotify-team/blob/main/Engineering/pull_request_labels.md#vanotify-labels) to the PR.
- [ ] I did not remove any parts of the template, such as checkboxes even if they are not used
- [ ] My code follows the [style guidelines](https://github.com/department-of-veterans-affairs/vanotify-team/blob/main/Process/style_guide.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to any documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works. [Testing guidelines](https://github.com/department-of-veterans-affairs/vanotify-team/blob/main/Process/testing_guide.md)
- [ ] I have ensured the latest main is merged into my branch and all checks are green prior to review
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] The ticket was moved into the DEV test column when I began testing this change

2024-11-21 22:07 UTC, cris-oddball requested changes
this cannot have the branch name in the pyproject.toml for utils.

2024-11-22 13:50 UTC, cris-oddball submitted a review, later dismissed

2024-11-22 14:47 UTC, EvanParish commented on .talismanrc
Why are there changes to this file?

2024-11-22 14:48 UTC, EvanParish submitted a review, later dismissed
It's weird that there are talisman changes, otherwise looks good.

2024-11-22 15:52 UTC, mchlwellman commented on .talismanrc
It appears to be sorted. Pre-commit maybe?

2024-11-22 17:05 UTC, k-macmillan approved these changes

2024-11-22 17:52 UTC, mchlwellman commented on .talismanrc
When I run `talisman -i -g pre-commit` to add the poetry lock file, it appears to sort these?

2024-11-22 17:53 UTC, k-macmillan approved these changes

2024-11-22 18:04 UTC, EvanParish commented on .talismanrc
Yeah, weird. Not really a big deal, but just thought it was odd. It's not anything we need to hold the PR up for.

2024-11-22 18:05 UTC, EvanParish approved these changes

2024-11-22 18:42 UTC, merged