VA Profile Sync - Update Lambda with the Comp & Pen Id Filter#684
department-of-veterans-affairs/notification-api pull request #722
Opened 2022-06-27 17:55 UTC by maham360

#684 

Updated lambda function with Comp & Pen ID filter to check if communicationChannelID is equal to 5 or not.
Wrote a unit test as a current placeholder because we have to test the PUT request first in another ticket #704, of which the format will change.

2022-06-27 20:53 UTC, kalbfled approved these changes

2022-06-28 14:26 UTC, jakehova requested changes

2022-06-28 14:26 UTC, jakehova commented on tests/lambda_functions/va_profile/test_va_profile_integration.py
> +    assert response["statusCode"] == 200
we should verify that no records in the database got changed.

2022-06-28 15:31 UTC, maham360 commented
Dave has a test to verify db writing scenarios so it would be repetitive to have it here. Wrote a unit test as a current placeholder because we have to test the PUT request first in another ticket https://github.com/department-of-veterans-affairs/notification-api/issues/704, of which the format will change.

2022-06-30 02:48 UTC, k-macmillan approved these changes

2022-06-30 12:59 UTC, EvanParish approved these changes

2022-06-30 13:31 UTC, jakehova approved these changes

2022-06-30 14:26 UTC, merged