VA Profile: Implement JWT Auth for POST endpoint
department-of-veterans-affairs/notification-api pull request #739
Opened 2022-07-06 19:23 UTC by kalbfled

#728

When VA Profile makes a POST request to update our local cache, they should include an asymmetrically signed [JWT](https://en.wikipedia.org/wiki/JSON_Web_Token).  We will receive these requests from Profile via AWS API Gateway v2, which proxies the request to our lambda with a specific [event format](https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway.html#apigateway-example-event) that I did not previously consider.  These updates:

- Update the lambda code to reflect the `event` it will actually receive
- Attempt to verify the JWT signature using an associated public key that is available in an env variable
- Update unit tests
- Include a minor README update 

I created a [PR in the infra repo](https://github.com/department-of-veterans-affairs/vanotify-infra/pull/392) to support changes required therein.

The changes in this PR also configure the local cache lambda to use the VA root pem to verify VA Profile's server when we make a PUT request to their endpoint.  Their server also authenticates our client (mTLS), but I haven't made any changes in this code to support that behavior.  I think their server will request and receive the default cert associated with our environment, and they can verify it with the VA room pem.

Note that these changes include an addition to requirements-for-test.txt.  Rebuild the test container before you run tests locally if you pull this branch or after this PR is merged.

Also note that these changes include several pem files for testing purposes.  One of these is a private key.  These pems are not used in any deployment environment.

2022-07-06 20:57 UTC, maham360 submitted a review, later dismissed

2022-07-06 21:20 UTC, kalbfled commented
I converted this PR to a draft because of the failing unit tests, which pass locally.  I deployed the associated infrastructure change to dev, verified the change in AWS Lambda console, and reran these remote tests.  The same tests failed again.

2022-07-21 15:33 UTC, kalbfled commented on ci/docker-compose-test.yml
> +      - VA_PROFILE_PUBLIC_KEY=test
It's wrong.

2022-07-21 15:55 UTC, jakehova requested changes

2022-07-21 15:55 UTC, jakehova commented on lambda_functions/va_profile/va_profile_opt_in_out_lambda.py
> +            Name=f"/{NOTIFY_ENVIRONMENT}/notification-api/va-profile/pem",
should this be va-root-pem?  I think I saw that in the infra repo

2022-07-21 15:55 UTC, jakehova commented on lambda_functions/va_profile/va_profile_opt_in_out_lambda.py
> +    if va_root_pem is not None and len(put_request_body["bios"]) > 0:
Can this just be: 

```
if va_root_pem is not None and put_request_body["bios"]:
```

2022-07-21 15:57 UTC, kalbfled commented on lambda_functions/va_profile/va_profile_opt_in_out_lambda.py
> +    if va_root_pem is not None and len(put_request_body["bios"]) > 0:
Can and should.  Will change.

2022-07-21 16:03 UTC, jakehova submitted a review, later dismissed

2022-07-21 16:12 UTC, k-macmillan commented
Need an expiration test in there. The agreed upon expiration of the JWT was 15 minutes.

2022-07-21 16:29 UTC, kalbfled commented on lambda_functions/va_profile/va_profile_opt_in_out_lambda.py
> +    logger.debug("VA_PROFILE_PUBLIC_KEY =\n", VA_PROFILE_PUBLIC_KEY)
```
>>> logger = logging.getLogger()
>>> logger.setLevel(logging.INFO)
>>> logger.info("Log this.\nAnd this.")
INFO:root:Log this.
And this.
```

2022-07-21 16:44 UTC, kalbfled commented on lambda_functions/va_profile/va_profile_opt_in_out_lambda.py
> +        the_pem = response.get("Parameter", {}).get("Value")
None is the default value.

2022-07-21 16:45 UTC, k-macmillan commented on lambda_functions/va_profile/va_profile_opt_in_out_lambda.py
> +    logger.debug("VA_PROFILE_PUBLIC_KEY =\n", VA_PROFILE_PUBLIC_KEY)
Wish I had an example so I knew what was done wrong in the ones that wouldn't put it on a newline. Oh well.

2022-07-21 16:47 UTC, kalbfled commented on lambda_functions/va_profile/va_profile_opt_in_out_lambda.py
> +    if not jwt_is_valid(headers.get("Authorization", headers.get("authorization", ''))):
The headers are user input, and I'm not sure if clients standardize capitalization.  This is my attempt to preclude an error.

2022-07-21 18:56 UTC, kalbfled commented on lambda_functions/va_profile/va_profile_opt_in_out_lambda.py
> +        jwt.decode(token, va_profile_public_cert, algorithms=["RS256"], options={"require": ["iat"]})
Added with additional unit tests.

2022-07-21 19:18 UTC, kalbfled commented on lambda_functions/va_profile/va_profile_opt_in_out_lambda.py
> +    logger.exception(e)
This is referring to an "except" block.

2022-07-21 19:18 UTC, kalbfled commented on lambda_functions/va_profile/va_profile_opt_in_out_lambda.py
> +
"except" block

2022-07-21 20:12 UTC, k-macmillan approved these changes

2022-07-21 21:38 UTC, EvanParish approved these changes

2022-07-21 22:10 UTC, merged