BUGFIX: Vetext two way lambda parsing bugfix
department-of-veterans-affairs/notification-api pull request #749
Opened 2022-07-19 16:57 UTC by jakehova

Bug fix to resolve issue with deserialization mms messages from twilio.  This required changes to how an alb event processes messages (namely uses dict instead of of json.loads and removes AddOns key/value from object) and sqs processes (uses json.loads).

Also added the unit testing file that I was using to test the lambda locally.

2022-07-19 18:19 UTC, kalbfled requested changes

2022-07-19 18:19 UTC, kalbfled commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
>      connection = http.client.HTTPSConnection(os.environ.get('vetext_api_endpoint_domain'),  context = ssl._create_unverified_context())
I know this isn't a current change, but . . .
```
connection = http.client.HTTPSConnection(os.getenv('vetext_api_endpoint_domain'),  context = ssl._create_unverified_context())
```

2022-07-19 18:19 UTC, kalbfled commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +    logger.debug(f"Retrieved queue_url: {queue_url}")
ditto C string formatting syntax

2022-07-19 18:19 UTC, kalbfled commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +def push_to_sqs(event_body):
I recommend returning a boolean indicating if the boto call succeeded.
```
def push_to_sqs(event_body: dict) -> bool:
```

2022-07-19 18:19 UTC, kalbfled commented on tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py
> +from unittest import mock
Do you need this?  You used the mocker fixture in your test functions.

2022-07-19 18:19 UTC, kalbfled commented on tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py
> +sqsInvokedWithAddOn =  {'Records': [{'messageId': '143555b0-a74b-4793-8421-15cfeeaa487d', 'receiptHandle': 'AQEBfoQLBPET91yTrBH2AEToheRAt2X8vrQddfzr8CG4haD0LT+leMdW7uiDW9AEvr6YMbTVBgYNSBUegTU/g3KQ6de
I would move these to another file, format them, and import them into this test.

2022-07-19 18:19 UTC, kalbfled commented on tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py
> +  assert response['statusCode'] == 424
ditto "failed dependency" ?

2022-07-19 18:41 UTC, jakehova commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +        logger.debug(f"Processing record body from SQS: {record['body']}")
Updated this to: 

```
event_body = record.get("body", "")

      if (event_body == ""):
          logger.info("event_body from sqs record was not present")
          logger.debug(record)
          continue

      logger.debug("Processing record body from SQS: %s", event_body)
      event_body = json.loads(record["body"])
      logger.info("Successfully converted record body from sqs to json")
      event_bodies.append(event_body)
```

There really shouldn't be an instance where body is empty or not present but if it is, then I'm just making note of it and moving to the next record in thee loop

2022-07-19 18:50 UTC, jakehova commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +    logger.debug(f"Retrieved queue_url: {queue_url}")
Changed to: 
```
logger.debug("Retrieved queue_url: %s", queue_url)
```

2022-07-19 20:54 UTC, k-macmillan requested changes

2022-07-19 20:54 UTC, k-macmillan commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +                logger.info("event_body from sqs record was not present")
```suggestion
                logger.info("event body from sqs record was not present")
```

2022-07-19 20:54 UTC, k-macmillan commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +            logger.debug("Processing record body from SQS: %s", event_body)
```suggestion
            logger.debug(f"Processing record body from SQS: {event_body}")
```

2022-07-19 20:54 UTC, k-macmillan commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +            logger.debug("Processing record body from SQS: %s", event_body)
I hope to never see a %s in python code ever again.

2022-07-19 20:54 UTC, k-macmillan commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +    logger.info(f"Decoded event_body {event_body_decoded}")
```suggestion
    logger.info(f"Decoded event body: {event_body_decoded}")
```

2022-07-19 20:54 UTC, k-macmillan commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +    logger.info("Converted body to dictionary")
```suggestion
    logger.info("Converted body to dictionary")
    logger.debug(f"Converted body dictionary: {event_body}")
```

2022-07-19 20:54 UTC, k-macmillan commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +    logger.info("Converted body to dictionary")
The body is more of a debug thing, and having that could help us to narrow down issues.

2022-07-19 20:54 UTC, k-macmillan commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +        del event_body['AddOns']
```suggestion
        event_body.pop('AddOns', None)
```

2022-07-19 20:54 UTC, k-macmillan commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +        del event_body['AddOns']
Del will result in a key error if it's not there. Use [pop](https://docs.python.org/3/library/stdtypes.html#dict.pop).

2022-07-19 20:54 UTC, k-macmillan commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +    logger.debug(json_data)
```suggestion
    logger.debug(f"json dumps: {json_data}")
```

2022-07-19 20:54 UTC, k-macmillan commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +    logger.debug(response.read().decode())
```suggestion
    logger.debug(f"VEText response: {response}")
```
We don't want to run read/decode on unverified data.

2022-07-19 20:54 UTC, k-macmillan commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +    logger.info("VeText call complete with response: %d", response.status)
```suggestion
    logger.info(f"VeText call complete with response: {response.status}")
```
No %s in python strings please unless necessary. Use f-strings.

2022-07-19 20:54 UTC, k-macmillan commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +        logger.debug("Retrieved queue_url: %s", queue_url)
```suggestion
        logger.debug(f"Retrieved queue_url: {queue_url}")
```

2022-07-19 21:31 UTC, k-macmillan requested changes

2022-07-19 21:31 UTC, k-macmillan commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +    logger.info(f"Decoded event body {event_body_decoded}")
```suggestion
    logger.debug(f"Decoded event body {event_body_decoded}")
```

2022-07-19 21:31 UTC, k-macmillan commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +    logger.info(f"Converted body to dictionary: {event_body}")
```suggestion
    logger.debug(f"Converted body to dictionary: {event_body}")
```

2022-07-19 21:31 UTC, k-macmillan commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +    logger.info("Placing event_body on retry queue")
```suggestion
    logger.info("Placing event_body on retry queue")
    logger.debug(f"Preparing for SQS: {event_body}")
```

2022-07-19 21:31 UTC, k-macmillan commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +                logger.debug(event_body)
```suggestion
```

2022-07-19 21:31 UTC, k-macmillan commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +                logger.debug(event_body)
```suggestion
```

2022-07-19 21:31 UTC, k-macmillan commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +        return True
```suggestion
```

2022-07-19 21:31 UTC, k-macmillan commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +        return False
```suggestion
```

2022-07-19 21:35 UTC, k-macmillan requested changes

2022-07-19 21:57 UTC, k-macmillan commented
Approving so the process isn't held up but this needs to be tested in Dev prior to a merge.

2022-07-19 21:58 UTC, k-macmillan submitted a review, later dismissed

2022-07-20 14:43 UTC, kalbfled requested changes
I like how you've parameterized tests.

I won't hold you up if you choose not to refactor to catch exceptions locally and return None or boolean values in functions, rather than letting exceptions bubble up and get caught at the top level, but I want to iterate that such changes would improve the execution flow and readability significantly.

2022-07-20 14:43 UTC, kalbfled commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +            if (event_body == ""):
```
if not event_body:
```

https://pep8.org/#string-quotes  <-- search for "empty"

2022-07-20 14:43 UTC, kalbfled commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +    if (event_body_encoded == ""):
Ditto.  This is a good place to return None.

2022-07-20 14:43 UTC, kalbfled commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +
remove

2022-07-20 14:43 UTC, kalbfled commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +    except KeyError as e:
remove

2022-07-20 14:43 UTC, kalbfled commented on tests/lambda_functions/vetext_incoming_forwarder_lambda/test_vetext_incoming_forwarder_lambda.py
> +    assert len(response) > 0
```
assert response, "The dictionary shouldn't be empty."
```
same pep8 reference as above

2022-07-20 15:05 UTC, kalbfled commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +    except KeyError as e:
It still shows that you have excess white space at the end.

2022-07-20 15:06 UTC, kalbfled commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +    if (event_body_encoded == ""):
```
if not even_body_encoded:
```

2022-07-20 15:07 UTC, kalbfled commented on lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py
> +
still shows white space

2022-07-20 15:16 UTC, kalbfled approved these changes

2022-07-20 16:47 UTC, k-macmillan approved these changes

2022-07-20 23:03 UTC, merged