Add MessageGroupId for fifo SQS
department-of-veterans-affairs/notification-api pull request #828
Opened 2022-09-09 19:55 UTC by ianperera

#827

# Description

Add MessageGroupId as a Parameter for sending SQS as fifo

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation changes only

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-09 20:41 UTC, k-macmillan requested changes

2022-09-09 20:41 UTC, k-macmillan commented on app/callback/sqs_client.py
> +                MessageGroupId=url if 'fifo' in url else None
You have to be careful with this. We don't know how they interpret "None", that's why I sent you the code I did. If you check their documentation:

>You can't use it for Standard queues.

Best to not include it. So your options are what I sent, an if/else block with duplicate code, or something else.

2022-09-09 20:43 UTC, k-macmillan commented on app/callback/sqs_client.py
> +                MessageGroupId=url if 'fifo' in url else None
I tried doing similar before with a different module but the default behavior was to set the unassigned parameters as instantiations of a class, so setting it to `None` broke it.

2022-09-13 19:49 UTC, jessecanderson approved these changes
Quick look compared to some of the doc's and it looks good to me.

2022-09-13 20:04 UTC, k-macmillan approved these changes

2022-09-13 20:11 UTC, merged