Testing pytest failure output
department-of-veterans-affairs/notification-api pull request #938
Opened 2022-11-04 03:50 UTC by trevor2718

2022-11-30 16:51 UTC, trevor2718 commented
See this for recent deploy (induced) error:
https://github.com/department-of-veterans-affairs/notification-api/actions/runs/3584681111/jobs/6031934116#step:3:42

2022-12-01 16:15 UTC, k-macmillan requested changes

2022-12-01 16:15 UTC, k-macmillan commented on lambda_functions/user_flows/user_flows_lambda.py
> +        # "--tb=short",
No need to have these comments

2022-12-01 16:27 UTC, cris-oddball requested changes

2022-12-01 16:27 UTC, cris-oddball commented on lambda_functions/user_flows/conftest.py
> +
This works for `service_test_api_key`, but there is another variable in use by the tests, which if those test fail, could then print out that variable: `service_api_key`. So this code need to look for both variables.

2022-12-06 19:52 UTC, cris-oddball submitted a review, later dismissed

2022-12-06 20:00 UTC, EvanParish approved these changes

2022-12-06 20:54 UTC, k-macmillan requested changes

2022-12-06 20:54 UTC, k-macmillan commented on lambda_functions/user_flows/test_retrieve_everything.py
> +    # below changed to "ses" per David
```suggestion
```

2022-12-06 21:06 UTC, EvanParish submitted a review, later dismissed

2022-12-06 21:32 UTC, cris-oddball approved these changes

2022-12-08 14:43 UTC, EvanParish approved these changes

2022-12-08 14:59 UTC, cris-oddball approved these changes

2022-12-08 15:01 UTC, merged